// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0v0t9KanfOYMH_WemU5bTNNKrc6B1yyo',
    appId: '1:613628922383:web:4ae42cd7f1affef5f4f17a',
    messagingSenderId: '613628922383',
    projectId: 'financepal-a1d63',
    authDomain: 'financepal-a1d63.firebaseapp.com',
    storageBucket: 'financepal-a1d63.appspot.com',
    measurementId: 'G-E7JV5F44RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnvobfEwu-91Y3UPo4FkTj0tBVU8MXgjY',
    appId: '1:613628922383:android:5ac6767309f56c61f4f17a',
    messagingSenderId: '613628922383',
    projectId: 'financepal-a1d63',
    storageBucket: 'financepal-a1d63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL23_d6KeOqpZx6-eW3WWQjoF_hAAh_5Q',
    appId: '1:613628922383:ios:c55e97555e369021f4f17a',
    messagingSenderId: '613628922383',
    projectId: 'financepal-a1d63',
    storageBucket: 'financepal-a1d63.appspot.com',
    iosClientId: '613628922383-25b33vk0c7u58odhelm3jtbeq2bqgpfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
